version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  publish_canary:
    executor: 
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          override-ci-command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: Prepare artifacts
          command: yarn bob pack-flat --commit $CIRCLE_BUILD_NUM
      - store_artifacts:
          path: .bob-packed
          destination: inspector