name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12, 14]
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - name: Bob, check the repo
        id: bob
        uses: 'kamilkisiela/bob@master'
      - name: Bob, check Test
        id: bob-test
        uses: 'kamilkisiela/bob@master'
        with:
          command: test
      - name: Bob, check Build
        id: bob-build
        uses: 'kamilkisiela/bob@master'
        with:
          command: build

      - uses: actions/cache@v2
        name: Cache node_modules
        if: steps.bob.outputs.dirty == 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        if: steps.bob.outputs.dirty == 'true'
        run: yarn

      - name: Build
        if: steps.bob-build.outputs.dirty == 'true'
        run: yarn affected:build

      - name: Test
        if: steps.bob-test.outputs.dirty == 'true'
        run: yarn affected:test
